name: CI

on:
  push:
    branches: main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.72.0
        with:
          components: clippy

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run linter
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.72.0
        with:
          components: clippy

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Compile tests
        run: cargo test --no-run

      - name: Run tests
        run: cargo nextest run

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.72.0
        with:
          components: rustfmt

      - name: Run formatter
        run: cargo fmt --all --check
